project:
  type: website

website:
  title: "PyVibLocalizer"
  repo-url: "https://github.com/KenHino/PyVibLocalizer"
  repo-actions: [edit, issue]
  navbar:
    right:
      - icon: github
        href: "https://github.com/KenHino/PyVibLocalizer"
      - href: index.qmd
        text: Home
      - Install.qmd
      - quick_start.ipynb
      - reference/index.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - quick_start.ipynb
      - reference/index.qmd
  page-footer: "Copyright 2024, Kentaro Hino" 


format:
  html:
    theme: united
    css: styles.css
    toc: true
    code-overflow: scroll
    code-fold: show
    code-tools: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    code-line-numbers: true
    code-link: true


quartodoc:
  package: pyvib
  parser: google
  render_interlinks: true
  title: "API Docs"
  sections:
    - title: "PyVib"
      desc: "Python package for vibration analysis"
      contents:
        - base.Vibration


